# Generated by Django 4.2.6 on 2023-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_contact_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConernImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='concernImages/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
