# Generated by Django 4.2.6 on 2023-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_concern_conernimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='context',
            field=models.CharField(default='fire', max_length=100),
            preserve_default=False,
        ),
    ]
